<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppLogger\AppLogger.csproj" />
    <ProjectReference Include="..\BrunoImporter\BrunoImporter.csproj" />
    <ProjectReference Include="..\CurlExporter\CurlExporter.csproj" />
    <ProjectReference Include="..\HttpAuth\HttpAuth.csproj" />
    <ProjectReference Include="..\HttpRequesting\HttpRequesting.csproj" />
    <ProjectReference Include="..\JsonFileStore\JsonFileStore.csproj" />
    <ProjectReference Include="..\SyntaxHighlighter\SyntaxHighlighter.csproj" />
    <ProjectReference Include="..\UrlQuery\UrlQuery.csproj" />
  </ItemGroup>

</Project>
